version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:80"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - EXTERNAL_API_KEY=your-key
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: fastapi-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
